## Import Necessary Modules 

In [1]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn import svm
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv("data.csv", sep = "\t")

data.head()

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00248942      F   0-17          10             A   
1  1000002  P00285442      M  25-35          16             C   
2  1000003  P00193542      M  26-35          15             A   
3  1000004  P00184942      M  46-50           7             B   
4  1000004  P00346142      M  46-50           7             B   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                           2               0                   1   
1                           5               0                   8   
2                           3               0                   1   
3                           2               1                   1   
4                           2               1                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0     15200  
1                15.0                10.0      7969  
2                 2.0                11.0     15227  
3                 8.0                17.0     19215  
4                15.0                10.0     15854

In [2]:
data.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

## Converting Objects to int using dictionary

In [3]:
data['Product_ID'].unique()

array(['P00248942', 'P00285442', 'P00193542', 'P00184942', 'P00346142',
       'P0097242', 'P00274942', 'P00251242', 'P00014542', 'P00031342',
       'P00145042', 'P00231342', 'P00190242', 'P0096642', 'P00058442',
       'P00036842', 'P00249542', 'P00220442', 'P00156442', 'P00213742',
       'P00214442', 'P00303442', 'P00135742', 'P00039942', 'P00161442',
       'P00078742', 'P00085942', 'P00118742', 'P00297942', 'P00266842',
       'P00058342', 'P00032442', 'P00105942', 'P00182642', 'P00186942',
       'P00155442', 'P00221342', 'P00087242', 'P00111142', 'P00259342',
       'P0094542', 'P00148642', 'P00312142', 'P00113242', 'P00192642',
       'P00110842', 'P00189642', 'P00304242', 'P00365242'], dtype=object)

In [4]:
c = 0
prod_dict = {}
for i in set(data.Product_ID):
    prod_dict[i] = c
    c = c+1
for i in range(len(data)):
    temp = data.Product_ID[i]
    data.Product_ID[i] = prod_dict[temp]

In [5]:
prod_dict

{'P00110842': 0,
 'P00274942': 1,
 'P00189642': 2,
 'P0094542': 3,
 'P00085942': 4,
 'P00193542': 5,
 'P00259342': 6,
 'P00036842': 7,
 'P0097242': 8,
 'P00058342': 9,
 'P00105942': 10,
 'P00192642': 11,
 'P00249542': 12,
 'P00032442': 13,
 'P00248942': 14,
 'P00182642': 15,
 'P00111142': 16,
 'P00184942': 17,
 'P00148642': 18,
 'P00113242': 19,
 'P00346142': 20,
 'P00213742': 21,
 'P00304242': 22,
 'P00155442': 23,
 'P00303442': 24,
 'P00118742': 25,
 'P00058442': 26,
 'P00135742': 27,
 'P00039942': 28,
 'P0096642': 29,
 'P00190242': 30,
 'P00220442': 31,
 'P00156442': 32,
 'P00231342': 33,
 'P00145042': 34,
 'P00251242': 35,
 'P00214442': 36,
 'P00297942': 37,
 'P00266842': 38,
 'P00186942': 39,
 'P00312142': 40,
 'P00087242': 41,
 'P00031342': 42,
 'P00365242': 43,
 'P00285442': 44,
 'P00078742': 45,
 'P00014542': 46,
 'P00221342': 47,
 'P00161442': 48}

In [6]:
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [7]:
c = 0
gender_dict = {}
for i in set(data.Gender):
    gender_dict[i] = c
    c = c+1
    
for i in range(len(data)):
    temp = data.Gender[i]
    data.Gender[i] = gender_dict[temp]

In [8]:
data['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [9]:
c = 0
city_dict = {}
for i in set(data.City_Category):
    city_dict[i] = c
    c = c+1
    
for i in range(len(data)):
    temp = data.City_Category[i]
    data.City_Category[i] = city_dict[temp]

In [10]:
data['Product_Category_2'].unique()

array([ 6., 15.,  2.,  8., 16.,  1., 11.,  0., 12.,  5.,  3., 14., 10.,
       nan,  4.,  7.,  9., 17., 13.])

In [11]:
c = 0
product_2_dict = {}
data.Product_Category_2 = data.Product_Category_2.fillna(0)
for i in set(data.Product_Category_2):
    product_2_dict[i] = c
    c = c+1
    
for i in range(len(data)):
    temp = data.Product_Category_2[i]
    data.Product_Category_2[i] = product_2_dict[temp]

In [12]:
data['Product_Category_3'].unique()

array([14., 10., 11., 17., 12.,  1.,  3., 15.,  5.,  4., 16.,  7.,  9.,
        8.,  6.,  2., nan, 13.])

In [13]:
c = 0
product_3_dict = {}
data.Product_Category_3 = data.Product_Category_3.fillna(0)
for i in set(data.Product_Category_3):
    product_3_dict[i] = c
    c = c+1
    
for i in range(len(data)):
    temp = data.Product_Category_3[i]
    data.Product_Category_3[i] = product_3_dict[temp]

In [14]:
data['Age'].unique()

array(['0-17', '25-35', '26-35', '46-50', '51-55', '36-45'], dtype=object)

In [15]:
c = 0
age_dict = {}
for i in set(data.Age):
    age_dict[i] = c
    c = c+1
    
for i in range(len(data)):
    temp = data.Age[i]
    data.Age[i] = age_dict[temp]

In [16]:
age_dict

{'51-55': 0, '26-35': 1, '25-35': 2, '36-45': 3, '0-17': 4, '46-50': 5}

In [17]:
data.head()

User_ID Product_ID Gender Age  Occupation City_Category  \
0  1000001         14      1   4          10             0   
1  1000002         44      0   2          16             1   
2  1000003          5      0   1          15             0   
3  1000004         17      0   5           7             2   
4  1000004         20      0   5           7             2   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                           2               0                   1   
1                           5               0                   8   
2                           3               0                   1   
3                           2               1                   1   
4                           2               1                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0     15200  
1                15.0                10.0      7969  
2                 2.0                11.0     15227  
3                 8.0                17.0     19215  
4                15.0                10.0     15854

In [18]:
data.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

## Splitting Data into Train and Test data sets 

In [19]:
from sklearn.model_selection import train_test_split
from sklearn import metrics # for checking the model accuracy


train, test = train_test_split(data, test_size=0.3) 


print(train.shape , test.shape)

(34, 12) (15, 12)


In [20]:
train_x = train[['Gender', 'Age', 'Occupation', 'City_Category',
                 'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
                 'Product_Category_2', 'Product_Category_3']]
train_y = train.Purchase

test_x = test[['Gender', 'Age', 'Occupation', 'City_Category',
                 'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
                 'Product_Category_2', 'Product_Category_3']]
test_y = test.Purchase 

## Applying Linear Regression Algorithm 

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


model = LinearRegression()
model.fit(train_x, train_y)

pred = model.predict(test_x)
pred1 = pred.astype(int)
print(metrics.accuracy_score(pred1, test_y))


from sklearn.metrics import mean_squared_error
from math import sqrt


rms = sqrt(mean_squared_error(pred1, test_y))
print(rms)


0.0
3531.923677922085


In [23]:
pred

array([ 3606.26162402,  9522.66387904, 16158.44556597, 11836.64075052,
        3398.7998104 ,  7619.35230467,  7506.17609685, 14468.79697063,
        6628.51243343, 16301.79522849, 10882.95521324, 15907.93658269,
       13568.65039147,  8752.57531314, 15488.88740381])

In [24]:
test['Lin_Prediction']= pred

In [25]:
test[['User_ID','Lin_Prediction','Purchase']]

User_ID  Lin_Prediction  Purchase
44  1000011     3606.261624      6171
41  1000010     9522.663879     12642
4   1000004    16158.445566     15854
45  1000011    11836.640751     19327
46  1000011     3398.799810      8027
42  1000010     7619.352305     10007
7   1000005     7506.176097      5254
33  1000010    14468.796971     12909
9   1000005     6628.512433      6073
21  1000008    16301.795228     11927
32  1000010    10882.955213      7089
15  1000007    15907.936583     11788
38  1000010    13568.650391     18963
27  1000010     8752.575313      8886
36  1000010    15488.887404     15705

## Applying Decision Tree Regressor Algorithm 

In [26]:
from sklearn.tree import DecisionTreeRegressor


model = DecisionTreeRegressor(max_depth=15, min_samples_leaf=100)

model.fit(train_x, train_y)

pred = model.predict(test_x)
pred1 = pred.astype(int)

print(metrics.accuracy_score(pred1, test_y))

from sklearn.metrics import mean_squared_error
from math import sqrt


rms = sqrt(mean_squared_error(pred1, test_y))
print(rms)

0.0
4516.817323440625


In [27]:
test['Tree_Prediction']= pred

In [28]:
test[['User_ID','Tree_Prediction','Purchase']]

User_ID  Tree_Prediction  Purchase
44  1000011     10493.117647      6171
41  1000010     10493.117647     12642
4   1000004     10493.117647     15854
45  1000011     10493.117647     19327
46  1000011     10493.117647      8027
42  1000010     10493.117647     10007
7   1000005     10493.117647      5254
33  1000010     10493.117647     12909
9   1000005     10493.117647      6073
21  1000008     10493.117647     11927
32  1000010     10493.117647      7089
15  1000007     10493.117647     11788
38  1000010     10493.117647     18963
27  1000010     10493.117647      8886
36  1000010     10493.117647     15705